<?php

// $Id: dashboard.info,v 1.4 2011/07/04 13:25:57 dries Exp $

/**
 * Implementation of hook_init
 */
function dashboard_init() {
//    drupal_add_css(drupal_get_path('module', 'dashboard') . '/css/dashboard.css', array('group' => CSS_DEFAULT, 'every_page' => TRUE));
}

/**
 * Implements hook_help().
 */
function dashboard_help($path, $arg) {
    switch ($path) {
        case 'admin/help#dashboard':
            $output = '<h3>' . t('About') . '</h3>';
            $output .= '<p>' . t('主页模块');
            return $output;
    }
}

/**
 * Implements hook_permission().
 */
function dashboard_permission() {
    return array(
        'dashboard' => array(
            'title' => t('主页'),
        ),
    );
}

function dashboard_menu() {
    $items = array();
    $items['dashboard'] = array(
        'title' => t('主页'),
        'page callback' => 'dashboard_call_back',
        'access arguments' => array('dashboard'),
        'weight' => -47,
    );

    $items['work/summary'] = array(
        'title' => t('工作'),
        'page callback' => 'work_summary_call_back',
        'access arguments' => array('dashboard'),
        'weight' => -47,
    );

    $items['work/enviro'] = array(
        'title' => t('环境未来'),
        'page callback' => 'work_enviro_call_back',
        'access arguments' => array('dashboard'),
        'weight' => -47,
    );

    $items['about/company'] = array(
        'title' => t('关于公司'),
        'page callback' => 'about_company_call_back',
        'access arguments' => array('dashboard'),
        'weight' => -47,
    );

    $items['about/team'] = array(
        'title' => t('关于团队'),
        'page callback' => 'about_team_call_back',
        'access arguments' => array('dashboard'),
        'weight' => -47,
    );
    
    return $items;
}

function dashboard_call_back() {
    $pageContent = '';
    return $pageContent;
}

function work_summary_call_back(){
    $pageContent = '';
    return $pageContent;
}

function work_enviro_call_back(){
    $pageContent = '';
    return $pageContent;
}

function about_company_call_back(){
    $pageContent = '';
    return $pageContent;
}

function about_team_call_back(){
    $pageContent = '';
    return $pageContent;
}